Fix another compile error:
> reactor-ts@0.0.1 check-types /Users/hokeunkim/Development/eclipses/lingua-franca-master/git/lingua-franca/org.lflang/src/lib/TS/reactor-ts
> tsc

src/core/reactor.ts:757:28 - error TS2729: Property 'reactor' is used before its initialization.

757         public util = this.reactor.util
                               ~~~~~~~

  src/core/reactor.ts:750:21
    750         constructor(private reactor: Reactor) {
                            ~~~~~~~~~~~~~~~~~~~~~~~~
    'reactor' is declared here.

Found 1 error.